export type User = {
  id: number;
  rank: number;
  name: string;
  points: number;
  avatar: string;
};

export const currentUser = {
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  ecoPoints: 1250,
  avatar: '4',
};

export const leaderboardData: User[] = [
  { id: 1, rank: 1, name: 'Jane Smith', points: 2500, avatar: '1' },
  { id: 2, rank: 2, name: 'EcoWarrior22', points: 2340, avatar: '2' },
  { id: 3, rank: 3, name: 'GreenThumb', points: 2100, avatar: '3' },
  { id: 4, rank: 4, name: 'Alex Doe', points: 1250, avatar: '4' },
  { id: 5, rank: 5, name: 'Captain Planet', points: 1100, avatar: '5' },
  { id: 6, rank: 6, name: 'RecycleRanger', points: 980, avatar: '6' },
  { id: 7, rank: 7, name: 'SolarSue', points: 850, avatar: '7' },
  { id: 8, rank: 8, name: 'WindyWill', points: 720, avatar: '8' },
];

export const quizzes = [
  {
    id: '1',
    title: 'Climate Change Basics',
    description: 'Test your knowledge on the fundamentals of climate change.',
    questions: 5,
    points: 50,
    category: 'Climate Science',
  },
  {
    id: '2',
    title: 'Waste Management & Recycling',
    description: 'How well do you know recycling and waste reduction?',
    questions: 8,
    points: 80,
    category: 'Sustainability',
  },
  {
    id: '3',
    title: 'Biodiversity and Ecosystems',
    description: 'Explore the variety of life on Earth.',
    questions: 7,
    points: 70,
    category: 'Biology',
  },
  {
    id: '4',
    title: 'Renewable Energy Sources',
    description: 'Learn about solar, wind, and other clean energies.',
    questions: 6,
    points: 60,
    category: 'Energy',
  },
];

export const quizDetails: Record<
  string,
  {
    id: string;
    title: string;
    questions: {
      question: string;
      options: string[];
      answer: string;
      explanation: string;
    }[];
  }
> = {
  '1': {
    id: '1',
    title: 'Climate Change Basics',
    questions: [
      {
        question:
          'Which of the following is the primary cause of recent climate change?',
        options: [
          'Volcanic eruptions',
          'Human activities',
          'Solar cycles',
          'Earths orbital changes',
        ],
        answer: 'Human activities',
        explanation:
          'The overwhelming scientific consensus is that human activities, especially the burning of fossil fuels, are the primary driver of recent climate change.',
      },
      {
        question: 'What is the "greenhouse effect"?',
        options: [
          'The cooling of the Earth',
          'The trapping of heat in the atmosphere',
          'The depletion of the ozone layer',
          'The coloring of plants',
        ],
        answer: 'The trapping of heat in the atmosphere',
        explanation:
          'The greenhouse effect is a natural process where certain gases in the atmosphere trap heat from the sun, which warms the Earth. Human activities have intensified this effect.',
      },
      {
        question: 'Which country is the largest current emitter of CO2?',
        options: ['United States', 'India', 'China', 'Russia'],
        answer: 'China',
        explanation:
          'As of recent data, China is the world\'s largest emitter of carbon dioxide, though historically, the United States has emitted the most cumulatively.',
      },
      {
        question:
          'What is a major potential impact of rising sea levels?',
        options: [
          'Creation of new beaches',
          'Increased coastal flooding and erosion',
          'More freshwater resources',
          'Cooler coastal temperatures',
        ],
        answer: 'Increased coastal flooding and erosion',
        explanation:
          'Rising sea levels, caused by melting ice sheets and thermal expansion of seawater, pose a significant threat to coastal communities through flooding and erosion.',
      },
      {
        question: 'What does "carbon footprint" refer to?',
        options: [
          'A type of fossil',
          'The amount of forest land',
          'The total greenhouse gases emitted by an individual or organization',
          'A brand of eco-friendly shoes',
        ],
        answer:
          'The total greenhouse gases emitted by an individual or organization',
        explanation:
          'A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.',
      },
    ],
  },
};

export const challenges = [
  {
    id: '1',
    title: 'Week-long Plastic-Free Challenge',
    description:
      'Attempt to use no single-use plastics for a full week. Track your progress and share your creative solutions.',
    points: 200,
    category: 'Waste Reduction',
  },
  {
    id: '2',
    title: 'Plant a Native Tree',
    description:
      'Plant a tree that is native to your region and help local biodiversity. Document the planting process.',
    points: 150,
    category: 'Reforestation',
  },
  {
    id: '3',
    title: 'DIY Compost Bin',
    description:
      'Build your own compost bin for kitchen scraps. Submit a photo or video of your creation and your first batch of compost.',
    points: 100,
    category: 'Gardening',
  },
  {
    id: '4',
    title: 'Meatless Monday',
    description:
      'Go vegetarian for one day a week. Share a photo of your delicious meat-free meal.',
    points: 50,
    category: 'Consumption',
  },
  {
    id: '5',
    title: 'Community Cleanup',
    description:
      'Organize or join a cleanup event in a local park, beach, or neighborhood. Submit a group photo!',
    points: 250,
    category: 'Community',
  },
];
